### ISSUE TITLE
no implicit conversion of Integer into String (TypeError)

### ISSUE THREAD

**Issue by andrewngo** [ruby/logger#107]
I don't have a repo without proprietary code yet but upgrading to 1.6.3 throws an error on my Windows machine. 

debugging, it looks like `dev.fileno` is an integer and it doesn't seem to like that
```
puts dev.fileno
3

puts dev.fileno.class
Integer

> File.new(dev.fileno, mode: MODE, path: filename)
*** TypeError Exception: no implicit conversion of Integer into String
```

```
no implicit conversion of Integer into String (TypeError)
from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `fixup_mode'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:123:in `create_logfile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:110:in `rescue in open_logfile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:106:in `open_logfile'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:85:in `set_dev'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger/log_device.rb:19:in `initialize'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger.rb:593:in `new'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/logger-1.6.3/lib/logger.rb:593:in `initialize'
<my code>
```

ruby -v
ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x64-mingw-ucrt]

**Comment by Watson1978** [comment]
I have same problem.

```ruby
require 'bundler/inline'
gemfile do
  source 'https://rubygems.org'
  # gem 'logger', '= 1.6.2'
  gem 'logger', '= 1.6.3'
end

require 'pathname'

path = Pathname.new('test.log')
logger = Logger.new(path)
```

```
PS C:\sandbox\ruby> ruby .\logger.rb
C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `initialize': no implicit conversion of Pathname into String (TypeError)

        dev = File.new(dev.fileno, mode: MODE, path: filename)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:99:in `fixup_mode'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:112:in `open_logfile'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:85:in `set_dev'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger/log_device.rb:19:in `initialize'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `new'
        from C:/Ruby33-x64/lib/ruby/gems/3.3.0/gems/logger-1.6.3/lib/logger.rb:593:in `initialize'
        from ./logger.rb:11:in `new'
        from ./logger.rb:11:in `<main>'
```

**Comment by Watson1978** [comment]
@nobu Can you look this issue ?
